ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.allow-http: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: ctfd-webservice@kubernetescrd
  hosts:
    - host: ctf.capturethe.camp
      path: "/"
  tls:
    - secretName: ctfcertificate
      hosts:
      - ctf.capturethe.camp
redis:
  global:
    storageClass: gp2
mariadb:
  persistence:
    storageClass: gp2
persistence:
  storageClass: gp2
