ingress:
  enabled: true
  hosts:
    - host: minced.capturethe.camp
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: mincedcertificate
      hosts:
      - minced.capturethe.camp
challenge:
  challenge: "md5collisionchallenge"
  flag: "md5collisionflag"
