apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ctfinfra
  name: secretinvasion
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets","secret"]
  verbs: ["get","list","list"]
