ingress:
  enabled: true
  hosts:
    - host: jsauth.capturethe.camp
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: jsauthcertificate
      hosts:
        - jsauth.capturethe.camp
challenge:
  challenge: "jsauth"
