ingress:
  enabled: true
  hosts:
    - host: subversion.capturethe.camp
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: subversioncertificate
      hosts:
        - subversion.capturethe.camp
challenge:
  challenge: "gitaccesschallenge"
  challengemountpath: /tmp/website/
  flag: gitaccessflag
command:
  - "/bin/sh"
args:
  - "-c"
  - "tar -xvf /tmp/website/localweb.tar -C /var/www/html/ && sed -i 's#Options -Indexes##' /etc/apache2/conf-enabled/docker-php.conf && apache2-foreground"
